task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0-snap
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --installdeps .
    - perl Makefile.PL
    - make
    - make test
